#Using java8
image: maven:3.3.9-jdk-8

#Currently only two stages configured for pipeline
stages:          
  - build
  - test

#Build stage to check for issues during compilation
compile-travel-agency-job:
  stage: build
  script:
    - echo "Compiling travel agency application..."
    - cd travelAgency
    - mvn clean compile
    - echo "Compilation successfully complete."
  tags:
    - ugrad

#Test stage to run tests and upload reports for analysis
test-travel-agency-job:
  stage: test
  script:
    - echo "Running tests...."
    - cd travelAgency
    - mvn test
    - echo "Successfully executed tests. Publishing results to GitLab..."
    #- mvn clean heroku:deploy-war
  artifacts:
    when: always
    reports:
      junit:
        - travelAgency/target/surefire-reports/TEST-*.xml #Reports are generated in target folder by surefire plugin.
        - travelAgency/target/failsafe-reports/TEST-*.xml #Reports are generated in target folder by surefire plugin.
  tags:
    - ugrad
